//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BMS.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Wraps a configuration attribute
	/// </summary>
	public class BMS_Attr<T>
	{
		/// <summary>
		/// The name of this attribute
		/// </summary>
		protected virtual string m_attrName
		{
			get;
			set;
		}

		/// <summary>
		/// The value of this attribute
		/// </summary>
		protected virtual T m_attrValue
		{
			get;
			set;
		}

		/// <summary>
		/// Retrieves the attribute type
		/// </summary>
		public virtual Type getAttrType()
		{
			throw new System.NotImplementedException();
		}

	}
}

